---
title: "d) Four sample plots"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{d) Four sample plots}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(biodata)
```

```{r}

# This script makes example of different kinds of plots using the telomere data 
# of Meillere et al 2015.

# Prep stuff
## libraries
library(ggpubr)
library(cowplot)
library(dplyr)
library(docxtractr)


file.url <-  "https://royalsocietypublishing.org/action/downloadSupplement?doi=10.1098%2Frsbl.2015.0559&file=rsbl20150559supp1.docx"

### Works with the URL too
file.docx <- docxtractr::read_docx(file.url)
docx.table.list <- docxtractr::docx_extract_all_tbls(docx = file.docx)


## Call each table from list
### nestlings
parus_telos_nest <- docx.table.list[[1]]



# clean up data
parus_telos_nest$cort <- as.numeric(parus_telos_nest$cort)
parus_telos_nest$telomere.length <- as.numeric(parus_telos_nest$telomere.length)

parus_telos_nest$Group <- with(parus_telos_nest,
                       paste(treatment,sex))

parus_telos_nest$Group <- gsub("control","Control",parus_telos_nest$Group)
parus_telos_nest$Group <- gsub("disturbed","Noise exposure",parus_telos_nest$Group)

parus_telos_nest$Group <- gsub(" F","\nFemales",parus_telos_nest$Group)
parus_telos_nest$Group <- gsub(" M","\nMales",parus_telos_nest$Group)
parus_telos_nest$cort.log <- log(parus_telos_nest$cort)
parus_telos_nest$telomere.length.log <- log(parus_telos_nest$telomere.length)


names(parus_telos_nest) <- gsub("treatment",
                        "Treatment",
                        names(parus_telos_nest))

names(parus_telos_nest) <- gsub("sex",
                        "Sex",
                        names(parus_telos_nest))

## Re-code data
dat.focal.cols <- parus_telos_nest[,c("Treatment","Sex","telomere.length","cort")]
dat.foc.cols.rnd <- dat.focal.cols
dat.foc.cols.rnd$telomere.length <- dat.foc.cols.rnd$telomere.length %>% round(1)
dat.foc.cols.rnd <- dat.foc.cols.rnd  %>% dplyr::arrange(Treatment,telomere.length)

## make plots
### make scatterplot
scatter. <- ggpubr::ggscatter(data = parus_telos_nest,
          y = "telomere.length",
          x = "cort",
          add = "reg.line",
          #color = white,
          cor.coef = T,
          title = "Scatter plot: 2 continous variables",
          xlab = "Predictor: Blood corticosterone\nconcentration",
          ylab = "Response: Telomere length\n")


### make bar plot
bar. <- ggpubr::ggbarplot(data = parus_telos_nest,
          y = "telomere.length",
          x = "Treatment",
          fill = "Treatment",
          palette = c("white","black"),
          add = "mean_ci",
          title = "Bar plot: means & error bars",
          xlab= "Predictor: Experimental group\n",
          ylab= "Response: Telomere length\n")


### make errror plot
error. <-
  ggpubr::ggerrorplot(data = parus_telos_nest,
          y = "telomere.length",
          x = "Group",
          desc_stat = "mean_ci",
          size =2,
          color = "Treatment"  , 
          title = "Error plot: means & error bars",
          xlab= "Predictor: Experimental group\n",
          ylab= "Response: Telomere length\n") 

### make histogram
hist. <- gghistogram(data = parus_telos_nest,
          x = "telomere.length",
          desc_stat = "mean_ci",
          title = "Histogram: Distribution of 1 variable",
          #fill = "sex",
          xlab  = "X-axis: Variable of interest\nTelomere length",
          ylab = "Y-axis: Number of observations\n")

### make boxplot
box. <- ggboxplot(data = parus_telos_nest,
          y = "telomere.length",
          x = "Treatment",
          fill = "Treatment",
          title = "Box plot: Distribution of 2 groups",
          xlab= "Predictor: Experimental group",
          ylab= "Response: Telomere length")

## Final output
###  plot all 4 plots in grid
plot_grid(hist.,    box.,
          scatter.,error.)
```

